# LLM-Fux Configuration
timeout: 600
data_dir: ./data
dataset: ""
outputs_dir: ./outputs

single_run:
  enabled: false
  file: Below_CantusFirmus_C
  model: gemini
  model_name: gemini-2.0-flash
  datatype: musicxml
  guide_path: data/guides/four-versus-one/4vs1_v1.0.txt
  temperature: 0.0
  max_tokens: 16000

batch_run:
  enabled: true
  models:
    - claude-opus-4-5
  datatypes:
    - musicxml
  files:
    - Above_CantusFirmus_C
    - Below_CantusFirmus_C
  contexts:
    - with
  guide_path: data/guides/four-versus-one/4vs1_v1.0.txt
  temperature: 0.0
  max_tokens: 16000
  parallel: 1
  retry: 0
